### ISSUE TITLE
Deprecation: Usage of `_actions` is deprecated

### ISSUE THREAD

**Issue by kliput** [martndemus/ember-invoke-action#6]
Hi, 
I'm using Ember 2.11.3 and ``invoke`` function of ember-invoke-action and I got below deprecation message: 

```
DEPRECATION: Usage of `_actions` is deprecated, use `actions` instead. [deprecation id: ember-runtime.action-handler-_actions]
        at logDeprecationStackTrace (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:16744:19)
        at HANDLERS.(anonymous function) (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:16855:7)
        at raiseOnDeprecation (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:16774:12)
        at HANDLERS.(anonymous function) (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:16855:7)
        at invoke (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:16871:7)
        at deprecate (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:16839:32)
        at Object.deprecate (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:28598:37)
        at Class.get (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:43094:21)
        at getActions (https://172.17.0.4:9443/js/panel-gui/assets/vendor.js:123841:18)
```

Best regards,
Jakub

**Comment by miguelcobain** [comment]
This is fixed on master and will be released on 1.5.1 version shortly.
